In [7]:
import pandas as pd

df_extracted = pd.read_csv("Test with manual labels.csv")
df_extracted = df_extracted[:60]
df_extracted

,ID,Land Surveyor,Surveyed For,Certified date,Total Area,Unit of Measurement,Address,Parish,LT Num
0,7703-078,Ronald R. Greene,Nero Millington,2020-09-14,430.8,sq m,Lot 636 Ruby Development,Davis,77.03.07.015
1,8606-095,Lennox J. Reid,Collymore Taylor,2021-10-14,428.7,sq m,Lot 7A Mangrove Park,Davis,86.06.07.090
2,7703-064,Ronald R. Greene,Frank Frank,2019-01-18,661.8,sq m,Lot 632 Ruby Development,Frank,77.03.08.034
3,7703-101,Michael L. Banfield,Smith Roachford,2022-08-27,527.3,sq m,"Lot 114 Ruby Park, Ruby Development",St. Philip,77.03.02.054
4,7707-114,Michael H Hutchinson,Liam Worrell,2013-02-07,540.4,sq m,Lot 224 Union Hall,St. Philip,77.07.06.028
5,8604-111,Andrew R. Bannister,Kerold Y. Davis,2013-10-14,1990.9,sq m,KIRTONS,SAINT PHILIP,86.04.02.011
6,7703-049,O'BRIEN ST.E WORRELL,Jones Emma,2016-06-03,602.5,sq m,"Lot 218, Ruby Development",St Philip,77.03.03.019
7,7706-060,Andre P.G. Clarke,Ann-Marie Warner,2016-12-28,4180.9,sq m,"Lot A, Union Road",St. Philip,77.06.03.016
8,7707-141,Lee B S Brathwaite,Henry V. Belgrave,2017-12-21,604.7,sq m,Lot 182 Union Hall,St. Philip,77.07.05.018
9,7707-152,Kenneth D. Ward,Jackson Jones,2018-07-27,580.2,sq m,"Lot 298, Union Hall Development",St. Philip,77.07.01.056
10,7706-062,Michelle E. St. Clair,Jackson Sealy,2019-01-19,1136.1,sq m,Lot 31 Crane Park North,St. Philip,77.06.05.031
11,7703-066,Michael H Hutchinson,RBC Royal Bank (Barbados) Ltd,2019-04-04,446.1,sq m,"Lot 613 Ruby Development, Stage 3, Part 2",St. Philip,77.03.08.013
12,8606-091,Nigel S. A. Lucas,Nola Smith,2019-07-04,430.3,sq m,LOT 5A MANGROVE PARK,ST. PHILIP,86.06.07.088
13,7703-071,Nigel S. A. Lucas,ESTLAN FIELDS,2020-02-18,583.6,sq m,LOT 437 RUBY DEVELOPMENT STAGE 3,ST.PHILIP,77.03.09.014
14,7703-072,Michael H Hutchinson,Elcena Nurse,2020-07-13,576.8,sq m,Lot 292 Ruby (Stage 2 Part 2),St. Philip,77.03.05.034
15,8604-128,Jennifer E. Alleyne,Alice L Grace,2020-09-24,1242.9,sq m,Lot 2 Kirtons,St. Philip,86.04.01.021
16,8605-014,Nigel S. A. Lucas,Alice THOMPSON,2021-09-20,485.0,sq m,"LOT 31 3RD. AVENUE FALCON CREST,OLDBURY",ST. PHILIP,86.05.03.031
17,8606-092,Michael H Hutchinson,Barbados Workers' Union,2020-12-07,440.6,sq m,Lot 26 Mangrove Park,St. Philip,86.06.06.007
18,7703-087,Andre P.G. Clarke,Cecily Charlie,2021-02-01,494.4,sq m,"Lot 372, Ruby Development (Stage 2 Part 2)",St. Philip,77.03.06.064
19,7702-112,Barry O. Haynes,RAHEEM DURANT,2022-07-02,1017.3,sq m,Davis Lane,St. Philip,77.02.01.014
20,7702-115,Lee B. S. Brathwaite,ARTHUR POUNDER,2023-07-05,1570.2,sq m,WORKHALL,St. Philip,77.02.03.067
21,7704-135,Andre P.G. Clarke,The Estate of Collymore Frank (dec'd) c/o Whit...,2023-11-02,1212.2,sq m,"Lot 4, Sea View",St. Philip,77.04.02.024
22,7704-137,Jamar Brathwaite,Kendra C. Holdip,2024-09-14,582.9,sq m,bordered (green & brown),St. Philip,77.04.04.053
23,8603-125,Michael H Hutchinson,Jackson V. White,2024-11-22,678.7,sq m,"Lot 154 Jones Gardens, Mangrove",St. Philip,86.03.04.064
24,7707-192,Jennifer E. Alleyne,Merville L Best,2023-11-13,592.1,sq m,Lot 74 Union Hall Development Stage 1,St. Philip,77.07.03.023
25,5601-027,Michael H Hutchinson,Sophia Williams,2013-03-19,833.5,sq m,Lot 2 Bayfield,St. Philip,56.01.01.024
26,7711-039,Michael H Hutchinson,Brown Wilson,2013-04-19,1705.1,sq m,"Lot 58 Crane Haven, Crane",St. Philip,77.11.04.058
27,7714-088,Andrew R. Bannister,Mrs. DAVIS St. Clair,2013-09-10,484.1,sq m,"LOT 32, COLLINGTON DRIVE, NEAR CRANE",SAINT PHILIP,77.14.03.032
28,7801-038,Michael H Hutchinson,Christopher H Beckley,2013-09-19,1518.4,sq m,Lot 18 Long Bay,St. Philip,78.01.02.018
29,5714-038,Michael H Hutchinson,Sophia E. Ivy McCollin L. Liam and Alyson R. M...,2013-11-19,737.1,sq m,"Lot 1 Coles Crescent, Coles",St. Philip,57.14.01.036
30,8709-083,Michael H Hutchinson,Sophia Wilson Diana,2013-12-05,423.4,sq m,Lot 22 Ocean City (Section B),St. Philip,87.09.03.022
31,8709-084,Michael H Hutchinson,Thomas Alice Davis,2013-06-05,423.4,sq m,Lot 23 Ocean City (Section B),St. Philip,87.09.03.023
32,4516-020,Andre P.G. Clarke,Williams Smith,2014-02-22,640.8,sq m,"Lot 128, Palm Springs I, White",St. Philip,45.16.03.045
33,7605-113,Kevin R. Belgrave,Wilson BARROW,2014-04-12,2033.5,sq m,MARCHFIELD,ST. PHILIP,76.05.01.006
34,8506-109,Andrew R. Bannister,Moore Charlie,2014-04-22,525.4,sq m,"LOT 10,WOODBOURNE TENANTRY",ST PHILIP,85.06.03.010
35,8503-092,H. A KING,Williams V.A. LYNCH,2014-05-03,677.5,sq m,"LOT 29, WOODBOURNE",ST. PHILIP,85.03.03.009
36,5514-025,Michael H Hutchinson,Frank D. Holder and Treesa Jack Holder,2014-06-09,1188.1,sq m,Lot 128 Mount Pleasant Gardens,St. Philip,55.14.01.028
37,8709-093,D.C. 'Vallen' Franklin JP.,Lucene Grace,2014-08-28,785.6,sq m,Lot 15 Ivy Development,St. Philip,87.09.07.015
38,7708-052,Michael H Hutchinson,Cleoner Ltd,2014-10-16,2993.9,sq m,Lot 184 Long Bay,St. Philip,77.08.03.080
39,7715-090,Kenneth D. Ward,Tayton Cot Services Ltd.,2014-11-11,1339.8,sq m,The Crane,St. Philip,77.15.08.009
40,5607-058,Nigel S. A. Lucas,St. Clair E. Anderson,2014-12-10,1007.9,sq m,"LOT 7, St. Clair VALE",ST. PHILIP,56.07.01.011
41,7615-029,Nigel S. A. Lucas,THE ESTATE OF Liam WEEKES,2014-12-10,2060.0,sq m,KIRTONS NO. 2,ST. PHILIP,76.15.05.004
42,5714-041,Kenneth D. Ward,The Estate of Collymore White (Dec'd),2015-05-22,2228.5,sq m,Coles,St. Philip,57.14.01.022
43,8702-050,Michael H Hutchinson,Doreen Small-Mason,2015-07-02,715.1,sq m,Lot 1 The Crane,St. Philip,87.02.03.002
44,5612-056,Nigel S. A. Lucas,Jackson Grant,2015-07-05,5852.0,sq m,EAST POINT,ST. Olivia,56.12.05.007
45,4516-024,Andrew R. Bannister,Thomas RAMSAY,2015-07-13,840.0,sq m,"LOT 197, COCO-DE-MER AVENUE, PALM SPRINGS, FOR...",ST. PHILIP,45.16.04.022
46,6806-058,Michael H Hutchinson,Vernon Moore,2015-10-06,4920.3,sq m,"Merricks, Nr Apple Hall",St. Philip,68.06.03.012
47,8616-026,H. A. KING,Moore LORD,2015-12-19,1137.5,sq m,"Lot-93, GREEN POINT, SECTION-2",ST. PHILIP,86.16.05.033
48,7605-123,Nigel S. A. Lucas,VIVIAN Taylor,2015-12-23,4028.0,sq m,MARCHFIELD,ST. PHILIP,76.05.03.002
49,5514-026,Kevin R. Belgrave,Taylor HEWITT,2016-02-06,693.8,sq m,"LOT 29, MOUNT PLEASANT GARDENS",ST. PHILIP,55.14.02.009
50,7605-127,Lennox J. Reid,White Blades,2016-02-19,2042.4,sq m,Thomas Harris,St. Philip,76.05.01.019
51,6813-044,Ronald R. Greene,Sophia Nurse,2016-04-20,335.9,sq m,"Eastbourne, Collymore (Lot 9).",St. Philip,68.13.01.077
52,7701-061,Lennox J. Reid,Olivia T. Bushelle,2016-04-20,2009.6,sq m,Duncans,St. Philip,77.01.03.032
53,7708-057,Andrew R. Bannister,Jackson SHEPHERD AND Diana SHEPHERD,2016-05-05,507.4,sq m,"LOT 94 ATLANTIC PARK, BELAIR",ST. PHILIP,77.08.02.069
54,7710-050,Andre P.G. Clarke,Chesterfield Olivia,2016-5-21,2714.9,sq m,Diamond Valley,St. Philip,77.10.01.006
55,8614-023,Michael H Hutchinson,Moore Mapp,2016-06-23,476.8,sq m,Lot 59 Gemswick Terrace,St. Philip,86.14.04.059
56,6507-068,Michael H Hutchinson,Anderson Liam,2016-06-29,470.7,sq m,Church Village,St. Philip,65.07.02.012
57,5605-047,Michael H Hutchinson,Thomas Hall-Harper,2016-07-29,2131.0,sq m,Bayfield,St. Philip,56.05.03.010
58,5611-033,Nigel S. A. Lucas,LIONEL BLADES,2016-08-04,826.2,sq m,"CLARKE'S HILL, NR.ST.CATHERINE'S",ST. PHILIP,56.11.02.013
59,7614-089,Lennox J. Reid,Nero Smith,2016-10-31,773.0,sq m,"Lot 3, Nursery #2, Four Roads",St Philip,76.14.06.040

In [ ]:
import re
import numpy as np

def clean_land_surveyor_names(names_array):
    """
    Clean land surveyor names by removing middle initials while preserving:
    - Names that start with initials (like H.A. King)
    - Names with nicknames in quotes
    - Names with compound elements like St. Clair
    - Professional designations like JP
    """

    def clean_single_name(name):
        if pd.isna(name) or not name or name.strip() == '':
            return name

        name = str(name).strip()

        # Skip names that start with initials (like "H.A King" or "H.A. King")
        if re.match(r'^[A-Z]\.?\s*[A-Z]\.?\s+', name):
          return name

        # Skip names with quotes (nicknames like D.C "Vallan" Franklin JP)
        if '"' in name:
            return name

        # Skip single names (like "Simba")
        if len(name.split()) <= 1:
            return name

        # Protect "St." in compound names like "Michelle E. St. Clair"
        name_protected = name.replace(' St. ', ' PROTECTED_ST ')

        # Remove middle initials patterns:
        # 1. Single initials: "Lennox J Reid" to "Lennox Reid"
        name_cleaned = re.sub(r'\s+[A-Z]\.?\s+', ' ', name_protected)

        # 2. Multiple initials: "Jamal K.L. Gaskin" to "Jamal Gaskin"
        name_cleaned = re.sub(r'\s+[A-Z]\.[A-Z]\.?\s+', ' ', name_cleaned)

        # 3. Space-separated initials: "Lee B S Brathwaite" to "Lee Brathwaite"
        name_cleaned = re.sub(r'\s+[A-Z]\s+[A-Z]\s+', ' ', name_cleaned)

        # 4. Complex patterns like "Lee B.S Brathwaite" or "Sekani H.C Franklin"
        name_cleaned = re.sub(r'\s+[A-Z]\.[A-Z]\s+', ' ', name_cleaned)

        # 5. Handle remaining single initials that might be left
        name_cleaned = re.sub(r'\s+[A-Z]\.?\s+', ' ', name_cleaned)

        # Restore protected "St."
        name_cleaned = name_cleaned.replace(' PROTECTED_ST ', ' St. ')

        # Clean up multiple spaces and trim
        name_cleaned = re.sub(r'\s+', ' ', name_cleaned).strip()

        return name_cleaned

    # Apply cleaning to each name in the array
    if isinstance(names_array, np.ndarray):
        return np.array([clean_single_name(name) for name in names_array])
    elif isinstance(names_array, (list, pd.Series)):
        return [clean_single_name(name) for name in names_array]
    else:
        return clean_single_name(names_array)

# Create working copy
data_expanded = df_extracted.copy()

# Apply to both name columns
data_expanded['Land Surveyor'] = clean_land_surveyor_names(data_expanded['Land Surveyor'])
data_expanded['Surveyed For'] = clean_land_surveyor_names(data_expanded['Surveyed For'])

print("Names cleaned (middle initials removed)")

In [9]:
def clean_target_survey(text: str) -> str:
    """Lowercase, remove periods and commas, normalize spaces"""
    text = text.lower()
    text = re.sub(r"[.,]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [ ]:
def format_dataset(df: pd.DataFrame) -> pd.DataFrame:
    """Create TargetSurvey and keep only required columns"""
    df["TargetSurvey"] = (
        df["Land Surveyor"].astype(str).str.strip() + " " +
        df["Surveyed For"].astype(str).str.strip() + " " +
        df["Address"].astype(str).str.strip()
    ).apply(clean_target_survey)

    columns_to_keep = [
        'ID', 'TargetSurvey', 'Certified date', 'Total Area',
        'Unit of Measurement', 'Parish', 'LT Num'
    ]
    return df[columns_to_keep]

final_data = format_dataset(data_expanded)

print("Final dataset created")
print(f"\nColumns: {final_data.columns.tolist()}")
print(f"\nTotal records: {len(final_data)}")
final_data.head(10)

In [11]:
# Save to CSV
final_data.to_csv('text_extraction_manual_labels_final.csv', index=False)

final_data

,ID,TargetSurvey,Certified date,Total Area,Unit of Measurement,Parish,LT Num
0,7703-078,ronald greene nero millington lot 636 ruby dev...,2020-09-14,430.8,sq m,Davis,77.03.07.015
1,8606-095,lennox reid collymore taylor lot 7a mangrove park,2021-10-14,428.7,sq m,Davis,86.06.07.090
2,7703-064,ronald greene frank frank lot 632 ruby develop...,2019-01-18,661.8,sq m,Frank,77.03.08.034
3,7703-101,michael banfield smith roachford lot 114 ruby ...,2022-08-27,527.3,sq m,St. Philip,77.03.02.054
4,7707-114,michael hutchinson liam worrell lot 224 union ...,2013-02-07,540.4,sq m,St. Philip,77.07.06.028
5,8604-111,andrew bannister kerold davis kirtons,2013-10-14,1990.9,sq m,SAINT PHILIP,86.04.02.011
6,7703-049,o'brien st e worrell jones emma lot 218 ruby d...,2016-06-03,602.5,sq m,St Philip,77.03.03.019
7,7706-060,andre clarke ann-marie warner lot a union road,2016-12-28,4180.9,sq m,St. Philip,77.06.03.016
8,7707-141,lee brathwaite henry belgrave lot 182 union hall,2017-12-21,604.7,sq m,St. Philip,77.07.05.018
9,7707-152,kenneth ward jackson jones lot 298 union hall ...,2018-07-27,580.2,sq m,St. Philip,77.07.01.056
10,7706-062,michelle st clair jackson sealy lot 31 crane p...,2019-01-19,1136.1,sq m,St. Philip,77.06.05.031
11,7703-066,michael hutchinson rbc royal bank (barbados) l...,2019-04-04,446.1,sq m,St. Philip,77.03.08.013
12,8606-091,nigel lucas nola smith lot 5a mangrove park,2019-07-04,430.3,sq m,ST. PHILIP,86.06.07.088
13,7703-071,nigel lucas estlan fields lot 437 ruby develop...,2020-02-18,583.6,sq m,ST.PHILIP,77.03.09.014
14,7703-072,michael hutchinson elcena nurse lot 292 ruby (...,2020-07-13,576.8,sq m,St. Philip,77.03.05.034
15,8604-128,jennifer alleyne alice grace lot 2 kirtons,2020-09-24,1242.9,sq m,St. Philip,86.04.01.021
16,8605-014,nigel lucas alice thompson lot 31 3rd avenue f...,2021-09-20,485.0,sq m,ST. PHILIP,86.05.03.031
17,8606-092,michael hutchinson barbados workers' union lot...,2020-12-07,440.6,sq m,St. Philip,86.06.06.007
18,7703-087,andre clarke cecily charlie lot 372 ruby devel...,2021-02-01,494.4,sq m,St. Philip,77.03.06.064
19,7702-112,barry haynes raheem durant davis lane,2022-07-02,1017.3,sq m,St. Philip,77.02.01.014
20,7702-115,lee brathwaite arthur pounder workhall,2023-07-05,1570.2,sq m,St. Philip,77.02.03.067
21,7704-135,andre clarke the estate of collymore frank (de...,2023-11-02,1212.2,sq m,St. Philip,77.04.02.024
22,7704-137,jamar brathwaite kendra holdip bordered (green...,2024-09-14,582.9,sq m,St. Philip,77.04.04.053
23,8603-125,michael hutchinson jackson white lot 154 jones...,2024-11-22,678.7,sq m,St. Philip,86.03.04.064
24,7707-192,jennifer alleyne merville best lot 74 union ha...,2023-11-13,592.1,sq m,St. Philip,77.07.03.023
25,5601-027,michael hutchinson sophia williams lot 2 bayfield,2013-03-19,833.5,sq m,St. Philip,56.01.01.024
26,7711-039,michael hutchinson brown wilson lot 58 crane h...,2013-04-19,1705.1,sq m,St. Philip,77.11.04.058
27,7714-088,andrew bannister mrs davis st clair lot 32 col...,2013-09-10,484.1,sq m,SAINT PHILIP,77.14.03.032
28,7801-038,michael hutchinson christopher beckley lot 18 ...,2013-09-19,1518.4,sq m,St. Philip,78.01.02.018
29,5714-038,michael hutchinson sophia ivy mccollin liam an...,2013-11-19,737.1,sq m,St. Philip,57.14.01.036
30,8709-083,michael hutchinson sophia wilson diana lot 22 ...,2013-12-05,423.4,sq m,St. Philip,87.09.03.022
31,8709-084,michael hutchinson thomas alice davis lot 23 o...,2013-06-05,423.4,sq m,St. Philip,87.09.03.023
32,4516-020,andre clarke williams smith lot 128 palm sprin...,2014-02-22,640.8,sq m,St. Philip,45.16.03.045
33,7605-113,kevin belgrave wilson barrow marchfield,2014-04-12,2033.5,sq m,ST. PHILIP,76.05.01.006
34,8506-109,andrew bannister moore charlie lot 10 woodbour...,2014-04-22,525.4,sq m,ST PHILIP,85.06.03.010
35,8503-092,h a king williams lynch lot 29 woodbourne,2014-05-03,677.5,sq m,ST. PHILIP,85.03.03.009
36,5514-025,michael hutchinson frank holder and treesa jac...,2014-06-09,1188.1,sq m,St. Philip,55.14.01.028
37,8709-093,d c 'vallen' franklin jp lucene grace lot 15 i...,2014-08-28,785.6,sq m,St. Philip,87.09.07.015
38,7708-052,michael hutchinson cleoner ltd lot 184 long bay,2014-10-16,2993.9,sq m,St. Philip,77.08.03.080
39,7715-090,kenneth ward tayton cot services ltd the crane,2014-11-11,1339.8,sq m,St. Philip,77.15.08.009
40,5607-058,nigel lucas st clair anderson lot 7 st clair vale,2014-12-10,1007.9,sq m,ST. PHILIP,56.07.01.011
41,7615-029,nigel lucas the estate of liam weekes kirtons ...,2014-12-10,2060.0,sq m,ST. PHILIP,76.15.05.004
42,5714-041,kenneth ward the estate of collymore white (de...,2015-05-22,2228.5,sq m,St. Philip,57.14.01.022
43,8702-050,michael hutchinson doreen small-mason lot 1 th...,2015-07-02,715.1,sq m,St. Philip,87.02.03.002
44,5612-056,nigel lucas jackson grant east point,2015-07-05,5852.0,sq m,ST. Olivia,56.12.05.007
45,4516-024,andrew bannister thomas ramsay lot 197 coco-de...,2015-07-13,840.0,sq m,ST. PHILIP,45.16.04.022
46,6806-058,michael hutchinson vernon moore merricks nr ap...,2015-10-06,4920.3,sq m,St. Philip,68.06.03.012
47,8616-026,h a king moore lord lot-93 green point section-2,2015-12-19,1137.5,sq m,ST. PHILIP,86.16.05.033
48,7605-123,nigel lucas vivian taylor marchfield,2015-12-23,4028.0,sq m,ST. PHILIP,76.05.03.002
49,5514-026,kevin belgrave taylor hewitt lot 29 mount plea...,2016-02-06,693.8,sq m,ST. PHILIP,55.14.02.009
50,7605-127,lennox reid white blades thomas harris,2016-02-19,2042.4,sq m,St. Philip,76.05.01.019
51,6813-044,ronald greene sophia nurse eastbourne collymor...,2016-04-20,335.9,sq m,St. Philip,68.13.01.077
52,7701-061,lennox reid olivia bushelle duncans,2016-04-20,2009.6,sq m,St. Philip,77.01.03.032
53,7708-057,andrew bannister jackson shepherd and diana sh...,2016-05-05,507.4,sq m,ST. PHILIP,77.08.02.069
54,7710-050,andre clarke chesterfield olivia diamond valley,2016-5-21,2714.9,sq m,St. Philip,77.10.01.006
55,8614-023,michael hutchinson moore mapp lot 59 gemswick ...,2016-06-23,476.8,sq m,St. Philip,86.14.04.059
56,6507-068,michael hutchinson anderson liam church village,2016-06-29,470.7,sq m,St. Philip,65.07.02.012
57,5605-047,michael hutchinson thomas hall-harper bayfield,2016-07-29,2131.0,sq m,St. Philip,56.05.03.010
58,5611-033,nigel lucas lionel blades clarke's hill nr st ...,2016-08-04,826.2,sq m,ST. PHILIP,56.11.02.013
59,7614-089,lennox reid nero smith lot 3 nursery #2 four r...,2016-10-31,773.0,sq m,St Philip,76.14.06.040